### ISSUE TITLE
problems installing...

### ISSUE THREAD

**Issue by limikael** [tunapanda/provision#31] opened 2014-12-29 09:57 UTC
I have some problems running this... I try to run it on a mac... There is a lot of output so trying select what might be interesting... The last working part looks like this:

````
TASK: [desktop | Gnome must be installed (this will take a while if it is not...)] *** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE apt name=edubuntu-desktop state=present
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/mikael/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile=/Users/mikael/Documents/repo/provision/.vagrant/machines/default/virtualbox/private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1419843733.04-99768917969438 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1419843733.04-99768917969438 && echo $HOME/.ansible/tmp/ansible-tmp-1419843733.04-99768917969438'"]
<127.0.0.1> PUT /var/folders/_z/f6ydvbs55cx_lmk1r4bnhlv80000gn/T/tmpGo9r7C TO /home/vagrant/.ansible/tmp/ansible-tmp-1419843733.04-99768917969438/apt
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/mikael/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile=/Users/mikael/Documents/repo/provision/.vagrant/machines/default/virtualbox/private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=cxwvvjunortiuiwoanngjwiwyhqmhnnr] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-cxwvvjunortiuiwoanngjwiwyhqmhnnr; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1419843733.04-99768917969438/apt; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1419843733.04-99768917969438/ >/dev/null 2>&1\'"\'"\'\'']
````

At this point it took a lot of time and a lot of error messages appears. It starts with...

````
failed: [default] => {"failed": true, "item": ""}
Extracting templates from packages: 100%
No apport report written because the error message indicates its a followup error from a previous failure.
E: Sub-process /usr/bin/dpkg returned an error code (1)
````

And ends with:

````
Extracting templates from packages: 100% ' failed: 
No apport report written because the error message indicates its a followup error from a previous failure.
E: Sub-process /usr/bin/dpkg returned an error code (1)


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/mikael/main.retry

default                    : ok=12   changed=8    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
````

Will try again and see if the same thing happens...

**Comment by limikael** [comment] 2015-01-02 08:38
Ok tried this... I removed the old clone I had and checked out everything fresh... And I assumed that in this case I should run `vagrant up` instead right? Got the following problem:

````
---
==> default: == Running core playbook
==> default: /tmp/vagrant-shell: line 212: popd: directory stack empty
==> default: ERROR: file could not read: /usr/local/tunapanda/provision/playbooks/profiles.yml
==> default: 
==> default: FATAL ERROR: Could not run core playbook
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

And I see that in the playbooks dir there is no profiles.yml file...

**Comment by usernamenumber** [comment] 2015-01-02 18:53
One of the problems I'm still wrestling with is getting each step of the bootstrapping process to use the same branch, which is what seems to be happening here. That, or you haven't pulled down the latest changes? I'll look into it. 

Worst-case scenario, once everything's merged into main it will be less of a problem.

**Comment by limikael** [comment] 2015-01-02 19:05
It should have been the latest, I removed the directory and cloned the
branch fresh. Not the master, but the other branch. Which one should I try?

Ok will try new updates continously. If anything, I can provide feedback on
weather it works intuitively out of the box for someone with limited
experience from these things, i.e. myself... :)
Den 2 jan 2015 19:53 skrev "Brad Smith" <notifications@github.com>:

**Comment by usernamenumber** [comment] 2015-01-03 10:29
I was able to reproduce the problem you saw, and have submitted a fix but have not had time to do a full test (provisioning a new VM from scratch) before needing to go to sleep. Try pulling and rebuilding yourself if you're feeling adventurous. Also, Vagrant will now pass certain env vars to the bootstrapping script, so try running `export PROVISION_CORE_VERSION=cubie_vagrant` before running vagrant and that *should* keep the branch consistent.

**Comment by usernamenumber** [comment] 2015-01-03 17:37
Tested. Should work. I'll create a tag or sub-branch I can use to track "last known good" in the future.

**Comment by usernamenumber** [comment] 2015-01-03 18:19
Ok, not sure it's the best solution long-term, but for now I'm using the tag `lng` to denote the most recent place in this branch where I've verified that a VM at least successfully provisions. You can clone it with:

  `git clone --recursive -b lng git@github.com:usernamenumber/provision.git`

**Comment by limikael** [comment] 2015-01-04 08:26
Ok will try this when I get a chance!

**Comment by limikael** [comment] 2015-01-04 19:32
Still having problems... :( This is the last screen of the output:

````
==> default: Processing triggers for man-db ...
==> default: Processing triggers for ureadahead ...
==> default: Processing triggers for install-info ...
==> default: Errors were encountered while processing:
==> default:  /var/cache/apt/archives/gcompris-data_12.01-0ubuntu1_all.deb
==> default: 
Extracting templates from packages: 54%buntu-desktop'' failed: 
Extracting templates from packages: 100%
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: 
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
==> default: 
==> default: PLAY RECAP ******************************************************************** 
==> default:            to retry, use: --limit @/root/main.retry
==> default: 
==> default: 127.0.0.1                  : ok=25   changed=11   unreachable=0    failed=1   
==> default: 
==> default: FATAL ERROR: Could not run core playbook
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

I cloned just now using:

    git clone -b cubie_vagrant --recursive https://github.com/usernamenumber/provision

Also tried:

    git clone --recursive -b lng git@github.com:usernamenumber/provision.git

But got:

````
Cloning into 'provision'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````

Which one should I use?

The contents of my localconfig.yml file, minus comments:

````
---
profiles: [ custom ] 

vars:
  desktop__enabled: true
  var1: "val1"
  var2: "val2"
  var3: "val3"
````

**Comment by usernamenumber** [comment] 2015-01-05 04:22
Sorry, that should have been:

`git clone --recursive -b lng https://github.com/usernamenumber/provision.git`

**Comment by usernamenumber** [comment] 2015-01-05 04:25
...as for the error you're seeing. Hmm, this looks weird:

```
Extracting templates from packages: 54%buntu-desktop'' failed: 
Extracting templates from packages: 100%
```

Unless it's just something off with your terminal, that `54%buntu` makes me wonder whether maybe there's some kind of corrupted name in the apt data. Let me know if you see this problem again with the `lng` tag...

**Comment by usernamenumber** [comment] 2015-01-05 08:30
BTW, it's still very much a work-in-progress, but I'm working on some [documentation of the provisioning process](https://github.com/tunapanda/provision/wiki/Setup), which you might find interesting. 

I've verified that a basic install (no desktop) works with each of the methods described in that doc. I've just started a GUI install with a localconfig similar to yours. Gotta sleep now, but will check back and troubleshoot as necessary in the morning.

While I'm still not sure what's causing the specific problem you saw, I did fix some bugs along the way, so try again when you have time?

**Comment by limikael** [comment] 2015-01-05 08:33
I did try it at home before I left this morning, and I still had some problems actually... :( I forgot to send it, I will do it when I get home...

**Comment by usernamenumber** [comment] 2015-01-05 16:28
When you can, try emailing me the entire output? I don't know if this could actually be contributing or not, but could it maybe be something about your locale settings?

**Comment by limikael** [comment] 2015-01-05 17:14
Here is the last page, will send the whole output in an email also...

````
==> default: Unpacking python-keyring (from .../python-keyring_0.9.2-0ubuntu0.12.04.2_all.deb) ...
==> default: Selecting previously unselected package python-launchpadlib.
==> default: Unpacking python-launchpadlib (from .../python-launchpadlib_1.9.12-1_all.deb) ...
==> default: Selecting previously unselected package python-apport.
==> default: Unpacking python-apport (from .../python-apport_2.0.1-0ubuntu17.8_all.deb) ...
==> default: Processing triggers for man-db ...
==> default: Processing triggers for ureadahead ...
==> default: ureadahead will be reprofiled on next reboot
==> default: Processing triggers for install-info ...
==> default: Processing triggers for ufw ...
==> default: Errors were encountered while processing:
==> default:  /var/cache/apt/archives/libbonobo2-common_2.32.1-0ubuntu1.1_all.deb
==> default: 
Extracting templates from packages: 13%E: Invalid archive signature
==> default: E: Prior errors apply to /var/cache/apt/archives/libbonobo2-common_2.32.1-0ubuntu1.1_all.deb
==> default: E: Prior errors apply to /var/cache/apt/archives/libidl-common_0.8.14-0.2ubuntu2_all.deb
==> default: E: Prior errors apply to /var/cache/apt/archives/libidl0_0.8.14-0.2ubuntu2_amd64.deb
==> default: E: Prior errors apply to /var/cache/apt/archives/liborbit2_1%3a2.14.19-0.1ubuntu1_amd64.deb
==> default: E: Prior errors apply to /var/cache/apt/archives/libbonobo2-0_2.32.1-0ubuntu1.1_amd64.deb
==> default: E: Prior errors apply to /var/cache/apt/archives/libglade2-0_1%3a2.6.4-1ubuntu1.1_amd64.deb
==> default: E: Prior errors apply to /var/cache/apt/archives/libtdb1_1.2.9-4_amd64.deb
==> default: E: Prior errors apply to /var/cache/apt/archives/libvorbisfile3_1.3.2-1ubuntu3_amd64.deb
==> default: debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 74%E: Invalid archive signature
==> default: E: Prior errors apply to /var/cache/apt/archives/khangman_4%3a4.8.3-0ubuntu0.1_amd64.deb
==> default: debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 100%
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: 
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
==> default: 
==> default: PLAY RECAP ******************************************************************** 
==> default:            to retry, use: --limit @/root/main.retry
==> default: 
==> default: 127.0.0.1                  : ok=25   changed=11   unreachable=0    failed=1   
==> default: FATAL ERROR: Could not run core playbook
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

**Comment by usernamenumber** [comment] 2015-01-25 16:21
This report is old, and a huge amount of changes have been implemented in #32. @limikael, if you get a chance to try testing with the new branch, that would be great.

**Closed by usernamenumber** 2015-01-25 16:21 UTC

**Comment by limikael** [comment] 2015-01-26 12:57
Yep! Tested it and it seems to work fine! Good job!

**Comment by limikael** [comment] 2015-01-26 12:57
(will provide some feedback on the mailinglist)

**Comment by usernamenumber** [comment] 2015-01-26 13:27
Great! Also, note that I have a branch for work on creating ansible roles for Swag, LearningLocker, and their dependencies:

  https://github.com/usernamenumber/provision/tree/swag

**Comment by usernamenumber** [comment] 2015-01-26 13:33
(if you start messing around with it, be sure to merge the current master branch into it first. also, I changed the default IP in the swag branch for some reason. Not a big deal, but should probably change it back)
